[platformio]
default_envs = nano_every

[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
monitor_speed = 115200

; Porting notes:
; - Arduino Nano / Uno can use the same source code.
; - For classic Nano, create an env with platform = atmelavr and board = nanoatmega328.
; - For Uno, create an env with platform = atmelavr and board = uno.
